/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantallasSolucion;

/**
 *
 * @author Personal
 */
public class JframePantallaAgregarPrenda extends javax.swing.JFrame {

    /**
     * Creates new form JframePantallaAgregarPrenda
     */
    public JframePantallaAgregarPrenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAgregarPrenda = new javax.swing.JTextField();
        txtAgregarPrecio = new javax.swing.JTextField();
        txtAgregarCodigo = new javax.swing.JTextField();
        btnAgregarPrenda = new javax.swing.JButton();
        btnCancelarPrenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Agregar Prenda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Agregar Nombre de Prenda:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Agregar Precio Prenda:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Agregar Codigo Prenda:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, 20));

        txtAgregarPrenda.setText("jTextField1");
        getContentPane().add(txtAgregarPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, -1));

        txtAgregarPrecio.setText("jTextField2");
        getContentPane().add(txtAgregarPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 280, -1));

        txtAgregarCodigo.setText("jTextField3");
        getContentPane().add(txtAgregarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 280, -1));

        btnAgregarPrenda.setBackground(new java.awt.Color(204, 0, 204));
        btnAgregarPrenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarPrenda.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarPrenda.setText("Agregar");
        getContentPane().add(btnAgregarPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 110, 40));

        btnCancelarPrenda.setBackground(new java.awt.Color(255, 153, 0));
        btnCancelarPrenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancelarPrenda.setText("Cancelar");
        getContentPane().add(btnCancelarPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePantallaAgregarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePantallaAgregarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePantallaAgregarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePantallaAgregarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePantallaAgregarPrenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPrenda;
    private javax.swing.JButton btnCancelarPrenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAgregarCodigo;
    private javax.swing.JTextField txtAgregarPrecio;
    private javax.swing.JTextField txtAgregarPrenda;
    // End of variables declaration//GEN-END:variables
}
