/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantallasSolucion;

/**
 *
 * @author Personal
 */
public class JframePantallaEliminarPrenda extends javax.swing.JFrame {

    /**
     * Creates new form JframePantallaEliminarPrenda
     */
    public JframePantallaEliminarPrenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarPrendaEliminar = new javax.swing.JTextField();
        txtBuscarEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEliminarPrenda = new javax.swing.JList<>();
        txtEliminarPrenda = new javax.swing.JButton();
        txtVolverPantalla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Eliminar Prenda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        txtBuscarPrendaEliminar.setText("jTextField1");
        getContentPane().add(txtBuscarPrendaEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 240, 30));

        txtBuscarEliminar.setBackground(new java.awt.Color(0, 255, 0));
        txtBuscarEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtBuscarEliminar.setText("Buscar");
        getContentPane().add(txtBuscarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 100, 30));

        listEliminarPrenda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listEliminarPrenda);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 370, 220));

        txtEliminarPrenda.setBackground(new java.awt.Color(255, 153, 0));
        txtEliminarPrenda.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEliminarPrenda.setForeground(new java.awt.Color(255, 255, 255));
        txtEliminarPrenda.setText("Eliminar Prenda");
        getContentPane().add(txtEliminarPrenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 120, 40));

        txtVolverPantalla.setBackground(new java.awt.Color(255, 0, 0));
        txtVolverPantalla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtVolverPantalla.setForeground(new java.awt.Color(255, 255, 255));
        txtVolverPantalla.setText("Volver");
        getContentPane().add(txtVolverPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 350, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePantallaEliminarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePantallaEliminarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePantallaEliminarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePantallaEliminarPrenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePantallaEliminarPrenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listEliminarPrenda;
    private javax.swing.JButton txtBuscarEliminar;
    private javax.swing.JTextField txtBuscarPrendaEliminar;
    private javax.swing.JButton txtEliminarPrenda;
    private javax.swing.JButton txtVolverPantalla;
    // End of variables declaration//GEN-END:variables
}
