/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PantallasSolucion;

/**
 *
 * @author Personal
 */
public class JframePantallaCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form JframePantallaCatalogo
     */
    public JframePantallaCatalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscarPrendacata = new javax.swing.JTextField();
        txtBuscarCatalogo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCatalogo = new javax.swing.JList<>();
        btnEliminarPantalla = new javax.swing.JButton();
        btnAgregarPantalla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Catalogo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 11, -1, -1));

        txtBuscarPrendacata.setText("jTextField1");
        getContentPane().add(txtBuscarPrendacata, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, 242, 30));

        txtBuscarCatalogo.setBackground(new java.awt.Color(102, 255, 0));
        txtBuscarCatalogo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtBuscarCatalogo.setText("Buscar");
        getContentPane().add(txtBuscarCatalogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 90, 30));

        listCatalogo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listCatalogo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 99, 360, 221));

        btnEliminarPantalla.setBackground(new java.awt.Color(255, 0, 0));
        btnEliminarPantalla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminarPantalla.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPantalla.setText("Eliminar Prenda");
        getContentPane().add(btnEliminarPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 40));

        btnAgregarPantalla.setBackground(new java.awt.Color(255, 153, 0));
        btnAgregarPantalla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAgregarPantalla.setText("Agregar Prenda");
        getContentPane().add(btnAgregarPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 130, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframePantallaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframePantallaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframePantallaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframePantallaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframePantallaCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPantalla;
    private javax.swing.JButton btnEliminarPantalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listCatalogo;
    private javax.swing.JButton txtBuscarCatalogo;
    private javax.swing.JTextField txtBuscarPrendacata;
    // End of variables declaration//GEN-END:variables
}
